### ISSUE TITLE
Fast tracking

### ISSUE THREAD

**Issue by jmmalaca** [mguinada/chr#1]
Hello mguinada,

I have followed your commits and read your code and nice work. Clean and total readable.
Now, imagine that this service is available and is been used by multiple machines that are calling the `/save` endpoint like crazy.

How can you make sure that the data isn't getting messy? Something like different calls, on the same time, about the same user, maybe having the same timestamp but different street or name.

And on the other side, if this machines are requesting the creation of data like crazy, we can have a huge amount of data. How can you make sure that if we call the `/changes` endpoint we will not be waiting big time?

Can your tell us your approach around these issues.

**Comment by mguinada** [comment]
Hi @tOOnPT,

Thanks for taking the time to go through the code.

For the high load and concurrency scenario you describe I would choose to implement a queue to mediate service calls and database writes. Service operations would push request data through the queue and a consumer would write sequentially to the database.  I would also look into the possibility of reinforcing data consistency at MongoDB level with [two-phase commits](https://docs.mongodb.com/v3.0/tutorial/perform-two-phase-commits/).

To deliver `/changes` responses gracefully I would implement pagination.
