### ISSUE TITLE
Global vars

### ISSUE THREAD

**Issue by donbonifacio** [mguinada/chr#2]
```clojure
(p/connect "challange")
```

On the service namespace you have this. This means that whenever you load this namespace, you'll connect to the database? How could you make this so that the connection would only be made when needed?

**Comment by mguinada** [comment]
I would wrap it in a function (e.g. `init!`) and call it at the application entry point `chr.web.service/run`.

**Comment by donbonifacio** [comment]
👍 

In here we use:
https://github.com/stuartsierra/component
