### ISSUE TITLE
Parallel parking

### ISSUE THREAD

**Issue by donbonifacio** [mguinada/chr#4]
Hello,

Somewhere down the line, this service is deployed/delivered via several machines and has a considerable load. Because of some reasons that you cannot control, you start receiving duplicate requests for the same data. For example: 

```
// request 1
{
  "_id": 1,
  "transactionId": "tx1",
  "name": "Bruce Willis",
  "address": {
    "street": "Nakatomi Plaza"
  }
}

// request 2
{
  "_id": 1,
  "transactionId": "tx1",
  "name": "Bruce Willis",
  "address": {
    "street": "Nakatomi Plaza"
  }
```

The systems that send these requests, also started sending a  `transactionId` that allows you to detect they are duplicate. For some more reasons, it's very problematic business wise to store duplicate data. You can only store one, even if you receive may. And all those many requests can be delivered at exactly the same time.

Can you elaborate on an approach to this?

**Comment by mguinada** [comment]
I could store `transactionId` and make a unique index on it. 
Alternatively or in conjunction with that, if the queue described at #1 was in place I could add request vetting at the consumer level by using an auxiliary database to keep track of transactions that were already processed.
